version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.1.0
  aws-ecr: circleci/aws-ecr@9.3.4
  node: circleci/node@6.1.0
  pulumi: pulumi/pulumi@2.1.0
  rollout: studion/rollout@0.1.1

studion-aws-credentials: &studion-aws-credentials
  role_arn: arn:aws:iam::${STUDION_AWS_ACCOUNT_ID}:role/circle_ci_starter
  region: ${STUDION_AWS_REGION}

executors:
  test:
    docker:
      - image: cimg/node:22.8.0
      - image: cimg/postgres:16.0
  node:
    docker:
      - image: cimg/node:22.8.0
  base:
    docker:
      - image: cimg/base:current
  playwright:
    docker:
      - image: mcr.microsoft.com/playwright:v1.47.2-noble
      - image: cimg/node:22.8.0
      - image: cimg/postgres:16.0

jobs:
  lint-client:
    working_directory: ./client
    executor: node
    steps:
      - checkout:
          path: ..
      - node/install-packages:
          override-ci-command: npm i
      - run:
          name: Lint client
          command: npm run lint
  lint-server:
    working_directory: ./server
    executor: node
    steps:
      - checkout:
          path: ..
      - node/install-packages:
          override-ci-command: npm i
      - run:
          name: Lint server
          command: npm run lint
  test-client:
    working_directory: ./client
    executor: playwright
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          app-dir: ../server
          override-ci-command: npm i
      - node/install-packages:
          override-ci-command: npm i
      - run:
          name: Install Playwright
          command: npx playwright install
      - run:
          name: Run tests
          command: npm test
          environment:
            DATABASE_HOST: localhost
            DATABASE_PORT: 5432
            DATABASE_NAME: circle_test
            DATABASE_USER: postgres
            VITE_AUTH0_DOMAIN: dev-6akn28u2adtkauhz.us.auth0.com
            VITE_AUTH0_CLIENT_ID: CA4vZt9hxJ3E6vEm8T9GVHS0XUouS3F5
            VITE_AUTH0_AUDIENCE: http://localhost:3000
            AUTH0_DOMAIN: dev-6akn28u2adtkauhz.us.auth0.com
            AUTH0_AUDIENCE: http://localhost:3000
            AUTH0_CLIENT_ID: 8zssnzjdMtmjYkyfqmST4Krjh6VBijNI
            AUTH0_CLIENT_SECRET: ${TEST_AUTH0_CLIENT_SECRET}
      - store_artifacts:
          path: playwright-report/index.html
  test-server:
    working_directory: ./server
    executor: test
    steps:
      - checkout:
          path: ..
      - node/install-packages:
          override-ci-command: npm i
      - run:
          name: Build server
          command: npm run build
      - run:
          name: Run tests
          command: npm test
          environment:
            DATABASE_HOST: localhost
            DATABASE_PORT: 5432
            DATABASE_NAME: circle_test
            DATABASE_USER: postgres
      - store_artifacts:
          path: coverage
  build-client:
    working_directory: ./client
    executor: node
    steps:
      - checkout:
          path: ..
      - node/install-packages:
          override-ci-command: npm ci
      - run:
          name: Build server
          command: npm run build
          environment:
            VITE_API_URL: https://api.starter.gostudion.com
            VITE_AUTH0_AUDIENCE: https://api.starter.gostudion.com
            VITE_AUTH0_DOMAIN: dev-6akn28u2adtkauhz.us.auth0.com
            VITE_AUTH0_CLIENT_ID: G0JUp8hOgPRpsDo4mcUSYUFrGhPQPk37
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - dist
  deploy:
    working_directory: ./infrastructure
    executor: node
    parameters:
      role_arn:
        type: string
      region:
        type: string
      account_id:
        type: string
      ecr_repo:
        type: string
      stack:
        type: string
    steps:
      - checkout:
          path: ..
      - attach_workspace:
          at: ..
      - aws-cli/setup:
          role_arn: << parameters.role_arn >>
          region: << parameters.region >>
      - run:
          name: Configure envs
          command: |
            echo 'export SERVER_IMAGE="<< parameters.account_id >>.dkr.ecr.<< parameters.region >>.amazonaws.com/<< parameters.ecr_repo >>:${CIRCLE_SHA1}"' >> "$BASH_ENV"
            source "$BASH_ENV"
      - pulumi/login
      - node/install-packages
      - pulumi/update:
          stack: << parameters.stack >>
          skip-preview: true
      - pulumi/stack_output:
          stack: << parameters.stack >>
          property_name: frontendBucketName
          env_var: S3_SITE_BUCKET
      - pulumi/stack_output:
          stack: << parameters.stack >>
          property_name: cloudfrontId
          env_var: CF_DISTRIBUTION_ID
      - aws-cli/setup:
          role_arn: << parameters.role_arn >>
          region: << parameters.region >>
      - run:
          name: Deploy to S3
          command: |
            aws s3 sync ../dist s3://${S3_SITE_BUCKET} --no-progress --delete
            aws s3 cp ../dist/admin.html s3://${S3_SITE_BUCKET}/admin --content-type 'text/html'
            aws cloudfront create-invalidation --distribution-id ${CF_DISTRIBUTION_ID} --paths "/*"

workflows:
  version: 2
  test:
    when:
      and:
        - not:
            equal: [master, << pipeline.git.branch >>]
    jobs:
      - lint-server
      - lint-client
      - test-server
      - test-client
      - rollout/build_and_push_server_to_aws_ecr:
          <<: *studion-aws-credentials
          account_id: ${STUDION_AWS_ACCOUNT_ID}
          repo_name: starter-app/dev
          dockerfile_dir: ./server
          build_dir: ./server
          requires:
            - test-server
  test-build-and-deploy:
    when:
      and:
        - equal: [master, << pipeline.git.branch >>]
    jobs:
      - test-server
      - test-client
      - build-client:
          requires:
            - test-client
      - rollout/build_and_push_server_to_aws_ecr:
          <<: *studion-aws-credentials
          account_id: ${STUDION_AWS_ACCOUNT_ID}
          repo_name: starter-app/dev
          dockerfile_dir: ./server
          build_dir: ./server
          requires:
            - test-server
      - deploy:
          <<: *studion-aws-credentials
          account_id: ${STUDION_AWS_ACCOUNT_ID}
          ecr_repo: starter-app/dev
          stack: dev
          requires:
            - rollout/build_and_push_server_to_aws_ecr
            - build-client
