version: 2.1
orbs:
  node: circleci/node@5.2.0

executors:
  node:
    docker:
      - image: cimg/node:22.8.0
      - image: cimg/postgres:16.0
  base:
    docker:
      - image: cimg/base:current
jobs:
  test-server:
    working_directory: ~/app/server
    executor: node
    environment:
      TEST_DB_URL: postgresql://postgres@localhost/circle_test
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          override-ci-command: npm i
      - run:
          command: npm run build
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-server
