version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-ecr: circleci/aws-ecr@9.0.4
  node: circleci/node@5.2.0
  pulumi: pulumi/pulumi@2.1.0

executors:
  node:
    docker:
      - image: cimg/node:22.8.0
  base:
    docker:
      - image: cimg/base:current
jobs:
  test:
    working_directory: ~/app
    executor: node
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm i
      - run:
          name: Run tests
          command: npm test

workflows:
    version: 2
    build-and-deploy:
      jobs:
        - test
