services:
  web:
    build:
      context: .
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_NAME=nest
      - DATABASE_USER=postgres
